### ISSUE TITLE
DESIGN UI Sketches

### ISSUE THREAD

**Issue by BayraktarBatuhan** [BayraktarBatuhan/StudentClub#2]
We need more screenshots.

**Comment by bbkutluer** [comment]
screenshots uploaded ..
![WhatsApp Image 2019-03-26 at 23 12 24 (9)](https://user-images.githubusercontent.com/48407572/55034176-8a88b700-501d-11e9-88c9-31cdeb304516.jpeg)
![WhatsApp Image 2019-03-26 at 23 12 24 (2)](https://user-images.githubusercontent.com/48407572/55034177-8b214d80-501d-11e9-93ff-2f903c0b471a.jpeg)
![WhatsApp Image 2019-03-26 at 23 12 24 (3)](https://user-images.githubusercontent.com/48407572/55034179-8b214d80-501d-11e9-8d2c-4e115fa97650.jpeg)
![WhatsApp Image 2019-03-26 at 23 12 24 (4)](https://user-images.githubusercontent.com/48407572/55034180-8b214d80-501d-11e9-8842-37686cfd2bcb.jpeg)
![WhatsApp Image 2019-03-26 at 23 12 24 (5)](https://user-images.githubusercontent.com/48407572/55034185-8bb9e400-501d-11e9-896b-66f31d1b4b33.jpeg)
![WhatsApp Image 2019-03-26 at 23 12 24 (6)](https://user-images.githubusercontent.com/48407572/55034186-8bb9e400-501d-11e9-8ac2-0ce8b67545b3.jpeg)
![WhatsApp Image 2019-03-26 at 23 12 24 (7)](https://user-images.githubusercontent.com/48407572/55034188-8bb9e400-501d-11e9-9e98-d574f6b4c702.jpeg)
![WhatsApp Image 2019-03-26 at 23 12 24 (8)](https://user-images.githubusercontent.com/48407572/55034189-8c527a80-501d-11e9-980e-181f05d3dea8.jpeg)
